### ISSUE TITLE
TypeError: check_inputs() takes from 6 to 9 positional arguments but 11 were given

### ISSUE THREAD

**Issue by DaLi-Jack** [chenhonghua/MVIP-NeRF#1]
Hi! Thanks for your great work!
I setup the environment according to your instructions and did not change any code, but encountered the following problem when running:
![image](https://github.com/chenhonghua/MVIP-NeRF/assets/70205757/95ce627a-3a79-40ac-b502-9a6f20f33c58)
How can I solve this problem? Looking forward to your reply!

**Comment by chenhonghua** [comment]
hi, I will check it next week

**Comment by chenhonghua** [comment]
hi, I just fixed this bug.

**Comment by DaLi-Jack** [comment]
yes! Thanks for your help.
