### ISSUE TITLE
Testing of the trained NeRF

### ISSUE THREAD

**Issue by jingyushi** [chenhonghua/MVIP-NeRF#11]
Hi,
Thanks for the good work again. Could you please also let us know how you run the test with your code on the test images in the SPINNeRF dataset, where the first forty are test images and the later sixty are train images? Thank you!

**Comment by jingyushi** [comment]
Could you also let us know or provide the bounding boxes for evaluating the masked area only? Thanks!

**Comment by chenhonghua** [comment]
Hi,

For the first question, you just need to use the fourth 40 poses to render the images from the trained NeRF. Then, we can evaluate them with GT.

For the second question, the bbox is calculated by the minimum x or y and maximum x or y of the mask.

**Comment by jingyushi** [comment]
Thank you so much!
