### ISSUE TITLE
IndexError when running the code.

### ISSUE THREAD

**Issue by DaLi-Jack** [chenhonghua/MVIP-NeRF#14]
Hi! Thanks for your great work. However, when I test your code, I encounter the following IndexError:
![image](https://github.com/user-attachments/assets/7fe3c6ce-b9f3-4eda-8694-2e63547895d9)
I haven't changed any of your code. How can I solve this problem?
I will be extremely grateful for any help!

**Comment by yxxshin** [comment]
Hello,

I changed the `run.py` part like this and got the codes working:

Before:
```python
if not args.prepare:                                               ################# modified #####################
    rays_rgb = rays_rgb[rays_rgb[:, :, 3] == 1].reshape(-1, 3, 4)  ################# modified #####################
    rays_inp = rays_inp[rays_rgb[:, :, 3] == 0].reshape(-1, 3, 4)       ################# modified #####################
```

After:
```python
if not args.prepare:                                               ################# modified #####################
    orig_rays_rgb = rays_rgb
    rays_rgb = rays_rgb[rays_rgb[:, :, 3] == 1].reshape(-1, 3, 4)  ################# modified #####################
    rays_inp = rays_inp[orig_rays_rgb[:, :, 3] == 0].reshape(-1, 3, 4)       ################# modified #####################
```

Try this !

**Comment by chenhonghua** [comment]
Hi,

I am not sure about this reason. If there is still an issue, I will run and check it.

thanks

**Comment by DaLi-Jack** [comment]
> Hello,
> 
> I changed the `run.py` part like this and got the codes working:
> 
> Before:
> 
> ```python
> if not args.prepare:                                               ################# modified #####################
>     rays_rgb = rays_rgb[rays_rgb[:, :, 3] == 1].reshape(-1, 3, 4)  ################# modified #####################
>     rays_inp = rays_inp[rays_rgb[:, :, 3] == 0].reshape(-1, 3, 4)       ################# modified #####################
> ```
> 
> After:
> 
> ```python
> if not args.prepare:                                               ################# modified #####################
>     orig_rays_rgb = rays_rgb
>     rays_rgb = rays_rgb[rays_rgb[:, :, 3] == 1].reshape(-1, 3, 4)  ################# modified #####################
>     rays_inp = rays_inp[orig_rays_rgb[:, :, 3] == 0].reshape(-1, 3, 4)       ################# modified #####################
> ```
> 
> Try this !

Yes! This solves the problem.
