### ISSUE TITLE
HI, I want to ask is this for train or test "python DS_NeRF/run.py --config DS_NeRF/config/config_1.txt"?

### ISSUE THREAD

**Issue by WarrenZZZZL** [chenhonghua/MVIP-NeRF#4]
And after I run this"python DS_NeRF/run.py --config DS_NeRF/config/config_1.txt", I can't find where the results are saved? The two problems is really confused me. Thank you.

**Comment by chenhonghua** [comment]
hi, results are save in the folder of basedir = ./logs_ours (see the config_1.txt).

video results and checkpoints will be saved according to the iterations ( i_video = 1500 and i_weights = 1500, respectively).
