### ISSUE TITLE
Multiview Score Distillation

### ISSUE THREAD

**Issue by jshifw** [chenhonghua/MVIP-NeRF#7]
Hi Chen,

Thanks for sharing your work and well-implemented code with all. Could you please show us how equation (9) was implemented in the code? It seems that the main for-loop inside train() is taking one image at each iteration and zero_grad() and step() within that iteration. How do you tackle the cross-view consistency (Sec. 3.5)? Thank you for sharing again!

**Comment by chenhonghua** [comment]
Hi, 

you can set is_colla_guidance = True to turn on the mult-view score distillation.

**Comment by jshifw** [comment]
Thank you!
