### ISSUE TITLE
hello, could you please release your dataset?

### ISSUE THREAD

**Issue by Arcxml** [chenhonghua/MVIP-NeRF#9]

**Comment by chenhonghua** [comment]
Sure, I will arrange it this weekend.

**Comment by Arcxml** [comment]
Thanks a lot



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/25/2024 14:24 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [chenhonghua/MVIP-NeRF] hello, could you please release your dataset? (Issue #9) |

Sure, I will arrange it this weekend.

**Comment by chenhonghua** [comment]
Hi, this is the Lama-inpainted images from SPIn-NeRF and Remove-NeRF, please cite SPIn-NeRF and Remove-NeRF if you use it. 
Link: https://drive.google.com/drive/folders/1cSX3nOd73dbLocVH__WjDcUy8Kr9wkyE?usp=sharing

**Comment by Arcxml** [comment]
thank you
